<<<<<<< HEAD
markdown: rdiscount 
=======
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title.html
name: "Xingfeng Si"
markdown: rdiscount

author: "Xingfeng"
atom-baseurl: "http://sixf.org"
disqus: "Xingfeng"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Vitea
    class: fa fa-film
    href: /about
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
>>>>>>> e54948daa8f9cf9da4182198125cab3f981bec9c

